[klone] ./configure GNU make check, ChangeLog update

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,13 +1,20 @@
 #!/bin/sh
 #
-# $Id: configure,v 1.73 2007/09/04 19:48:39 tat Exp $
+# $Id: configure,v 1.74 2007/10/09 16:05:31 tat Exp $
 
 export makl_conf_h=klone_conf.h
 export MAKL_DIR=`pwd`/makl
 
+if [ -z "$MAKE" ]; then
+    MAKE=make
+fi
+
+# will fail using something different then GNU make
+${MAKE} -C build/makecheck || exit 1
+
 # before running configure the toolchain must be present
 if [ ! -r ${MAKL_DIR}/etc/toolchain.cf ]; then
-    make -C ${MAKL_DIR} toolchain
+    ${MAKE} -C ${MAKL_DIR} toolchain
 fi
 
 # MaKL preamble
